#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 24 11:42:49 2024

@author: arturo
"""

import pandas as pd
import openpyxl
from openpyxl import Workbook

les = 2022
workbook3 = openpyxl.load_workbook('/home/arturo/Downloads/prb1.xlsx')
h=workbook3['CAL']
tt=h.cell(row=108, column=16)
print(tt.value)
tt.value = les
workbook3.save('/home/arturo/Downloads/'+str(les)+'.xlsx')
